controller:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi

api:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi

garbageCollector:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi

externalWebhooksServer:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi

managementController:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi

webhooksServer:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi