apiVersion: v1
kind: Secret
metadata:
  name: reference-service-go-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: 'https://github.com/monkescience/reference-service-go.git'
