apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: alloy-config
    files:
      - loki-writer.alloy
      - prometheus-writer.alloy
      - node-logs.alloy
      - pod-logs-discovery.alloy
      - pod-logs.alloy
      - cluster-events.alloy
      - grafana-operator-metrics.alloy
